sudo: false
language: node_js

node_js:
- 12

cache:
  directories:
  - node_modules

branches:
  only:
  - master

install:
- bash install.sh

script:
- bash generate.sh
- bash -c "echo wiki.noodlefighter.com > hexo/public/CNAME"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir:
    hexo/public
