sudo: false
language: node_js

node_js:
- 12

cache:
  directories:
  - node_modules

branches:
  only:
  - master

install:
- bash install.sh

script:
- bash generate.sh

after_script:
- cd hexo
- hexo d